# Copyright (C) 2025 bytesatwork AG - https://www.bytesatwork.io
# Released under the MIT license (see COPYING.MIT for the terms)

#@TYPE: Machine
#@NAME: byteDEVKIT STM32MP2
#@DESCRIPTION: byteDEVKIT STM32MP2 by bytesatwork AG

require include/byteengine-stm32mp2.inc

# Do not remove any partitions from rootfs (/boot is needed for rauc)
PARTITIONS_MOUNTPOINT_IMAGE:remove = "${STM32MP_BOOTFS_MOUNTPOINT_IMAGE}"
PARTITIONS_MOUNTPOINT_IMAGE:remove = "${STM32MP_USERFS_MOUNTPOINT_IMAGE}"
PARTITIONS_MOUNTPOINT_IMAGE:remove = "${STM32MP_VENDORFS_MOUNTPOINT_IMAGE}"

IMAGE_FSTYPES:remove = "ext4"

STM32MP_DEVICETREE = "stm32mp257f-bytedevkit"
BOOTSCHEME_LABELS = "optee"

STM32MP_DEVICETREE_PROGRAMMER_ENABLE = "0"

# U-boot extra configuration
UBOOT_CONFIG = "default_stm32mp25"
UBOOT_CONFIG[default_stm32mp25] = "stm32mp257_bytedevkit_defconfig,,u-boot.dtb"
UBOOT_DEVICETREE[default_stm32mp25] = "stm32mp257f-bytedevkit"

# build tf-a artifacts for SD card
STM32MP_DT_FILES_SDCARD = "stm32mp257f-bytedevkit"

WKS_FILE = "stm32mp2-sdcard-tfa-optee.wks"
WKS_FILE_DEPENDS ?= " \
    virtual/bootloader \
    virtual/trusted-firmware-a \
    ${@bb.utils.contains('BOOTSCHEME_LABELS', 'optee', 'virtual-optee-os', '', d)} \
"
